uploader:
  qiniu:
    accessKey:
    secretKey:
  cos:
    secretId:
    secretKey:
  alioss:
    accessKey:
    accessKeySecret:

demo:
  editDisabled: true

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://172.17.0.1:13306/d2p_pm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true

server:
  url:
    prefix: /api